language: java
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
sudo: required
services:
  - docker
before_install:
  - docker run -d -p 10101:10101 pilosa/pilosa:v0.3.2
script:
  - mvn -f com.pilosa.client/pom.xml clean test failsafe:integration-test jacoco:report coveralls:report

