language: java
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
sudo: required
group: deprecated-2017Q2
before_install:
  - curl -o pilosa https://storage.googleapis.com/pilosa/pilosa-sumreduce && chmod +x pilosa && ./pilosa server &
script:
  - mvn -f com.pilosa.client/pom.xml clean test failsafe:integration-test jacoco:report coveralls:report

